//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0

use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[derive(Clone, Debug, PartialEq, Eq, DeriveEntityModel, Serialize, Deserialize)]
#[sea_orm(table_name = "liquidity_events")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false)]
    pub tx_hash: String,
    pub block_hash: String,
    #[sea_orm(primary_key, auto_increment = false)]
    pub log_index: i32,
    pub contract_address: String,
    pub event_type: String,
    pub amount_usdc: String,
    pub amount_usdt: String,
    pub amount_stb: String,
    pub receiver: String,
    pub block_number: i64,
    pub block_timestamp: i64,
    #[sea_orm(primary_key, auto_increment = false)]
    pub chain_id: i32,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {}

impl ActiveModelBehavior for ActiveModel {}
